services:

  db-webdinamis:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: Admin@84197
      MARIADB_DATABASE: dbcompro_2388010020
      MARIADB_USER: userwebdinamis_2388010020
      MARIADB_PASSWORD: usrcompro_2388010020
    volumes:
      - db_data:/var/lib/mysql
      - /home/ubuntu/docker-aws/db_data/dbcompro_2388010020.sql:/docker-entrypoint-initdb.d/dbcompro_2388010020.sql:ro
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - uasnet

  container-statis:
    image: faqih703/uas_statis:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - uasnet

  container-dinamis:
    image: faqih703/uas_dinamis:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_USER: userwebdinamis_2388010020
      DB_PASSWORD: usrcompro_2388010020
      DB_NAME: dbcompro_2388010020
      DB_HOST: db-webdinamis
      AUTH_TRUST_HOST: "true"
      NEXTAUTH_SECRET: adm-serv-web-bebas-saja-32-karakter
      NEXTAUTH_URL: http://54.254.58.193:3000
    depends_on:
      db-webdinamis:
        condition: service_healthy
    networks:
      - uasnet

volumes:
  db_data: {}

networks:
  uasnet:
    driver: bridge
